// flow-typed signature: 2d25275d7425a41888fb32919ef5c369
// flow-typed version: <<STUB>>/shopify-buy_v^2.2.3/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shopify-buy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shopify-buy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shopify-buy/index.amd' {
  declare module.exports: any;
}

declare module 'shopify-buy/index.es' {
  declare module.exports: any;
}

declare module 'shopify-buy/index.umd' {
  declare module.exports: any;
}

declare module 'shopify-buy/index.umd.min' {
  declare module.exports: any;
}

declare module 'shopify-buy/index.unoptimized.umd' {
  declare module.exports: any;
}

declare module 'shopify-buy/index.unoptimized.umd.min' {
  declare module.exports: any;
}

declare module 'shopify-buy/rollup-browser-tests.config' {
  declare module.exports: any;
}

declare module 'shopify-buy/rollup-common.config' {
  declare module.exports: any;
}

declare module 'shopify-buy/rollup-node-tests.config' {
  declare module.exports: any;
}

declare module 'shopify-buy/rollup-tests-common.config' {
  declare module.exports: any;
}

declare module 'shopify-buy/rollup-unoptimized.config' {
  declare module.exports: any;
}

declare module 'shopify-buy/scripts/livereload' {
  declare module.exports: any;
}

declare module 'shopify-buy/scripts/rollup-plugin-eslint-test-generator' {
  declare module.exports: any;
}

declare module 'shopify-buy/scripts/upload-to-cdn' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shopify-buy/index.amd.js' {
  declare module.exports: $Exports<'shopify-buy/index.amd'>;
}
declare module 'shopify-buy/index.es.js' {
  declare module.exports: $Exports<'shopify-buy/index.es'>;
}
declare module 'shopify-buy/index' {
  declare module.exports: $Exports<'shopify-buy'>;
}
declare module 'shopify-buy/index.js' {
  declare module.exports: $Exports<'shopify-buy'>;
}
declare module 'shopify-buy/index.umd.js' {
  declare module.exports: $Exports<'shopify-buy/index.umd'>;
}
declare module 'shopify-buy/index.umd.min.js' {
  declare module.exports: $Exports<'shopify-buy/index.umd.min'>;
}
declare module 'shopify-buy/index.unoptimized.umd.js' {
  declare module.exports: $Exports<'shopify-buy/index.unoptimized.umd'>;
}
declare module 'shopify-buy/index.unoptimized.umd.min.js' {
  declare module.exports: $Exports<'shopify-buy/index.unoptimized.umd.min'>;
}
declare module 'shopify-buy/rollup-browser-tests.config.js' {
  declare module.exports: $Exports<'shopify-buy/rollup-browser-tests.config'>;
}
declare module 'shopify-buy/rollup-common.config.js' {
  declare module.exports: $Exports<'shopify-buy/rollup-common.config'>;
}
declare module 'shopify-buy/rollup-node-tests.config.js' {
  declare module.exports: $Exports<'shopify-buy/rollup-node-tests.config'>;
}
declare module 'shopify-buy/rollup-tests-common.config.js' {
  declare module.exports: $Exports<'shopify-buy/rollup-tests-common.config'>;
}
declare module 'shopify-buy/rollup-unoptimized.config.js' {
  declare module.exports: $Exports<'shopify-buy/rollup-unoptimized.config'>;
}
declare module 'shopify-buy/scripts/livereload.js' {
  declare module.exports: $Exports<'shopify-buy/scripts/livereload'>;
}
declare module 'shopify-buy/scripts/rollup-plugin-eslint-test-generator.js' {
  declare module.exports: $Exports<'shopify-buy/scripts/rollup-plugin-eslint-test-generator'>;
}
declare module 'shopify-buy/scripts/upload-to-cdn.js' {
  declare module.exports: $Exports<'shopify-buy/scripts/upload-to-cdn'>;
}
