export const PRODUCT_LIST_QUERY = 'PRODUCT_LIST_QUERY';
export const COLLECTION_PRODUCT_LIST_QUERY = 'COLLECTION_PRODUCT_LIST_QUERY';
export const COLLECTION_LIST_QUERY = 'COLLECTION_LIST_QUERY';

export const CART_QUERY = 'CART_QUERY';
export const CART_ITEM_COUNT_QUERY = 'CART_ITEM_COUNT_QUERY';
