export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';

export const GET_FIRST_PAGE_OF_PRODUCTS_REQUEST = 'GET_FIRST_PAGE_OF_PRODUCTS_REQUEST';
export const GET_FIRST_PAGE_OF_PRODUCTS_FAILURE = 'GET_FIRST_PAGE_OF_PRODUCTS_FAILURE';
export const GET_FIRST_PAGE_OF_PRODUCTS_SUCCESS = 'GET_FIRST_PAGE_OF_PRODUCTS_SUCCESS';

export const GET_NEXT_PAGE_OF_PRODUCTS_REQUEST = 'GET_NEXT_PAGE_OF_PRODUCTS_REQUEST';
export const GET_NEXT_PAGE_OF_PRODUCTS_FAILURE = 'GET_NEXT_PAGE_OF_PRODUCTS_FAILURE';
export const GET_NEXT_PAGE_OF_PRODUCTS_SUCCESS = 'GET_NEXT_PAGE_OF_PRODUCTS_SUCCESS';

export const ADD_VARIANT_TO_CART_REQUEST = 'ADD_VARIANT_TO_CART_REQUEST';
export const ADD_VARIANT_TO_CART_FAILURE = 'ADD_VARIANT_TO_CART_FAILURE';
export const ADD_VARIANT_TO_CART_SUCCESS = 'ADD_VARIANT_TO_CART_SUCCESS';
