query getCart($checkoutId: ID!) {
  node(id: $checkoutId) {
    ... on Checkout {
      __typename
      webUrl
      subtotalPriceV2 {
        amount
        currencyCode
      }
      totalTaxV2 {
        amount
        currencyCode
      }
      totalPriceV2 {
        amount
        currencyCode
      }
      lineItems(first: 250) {
        edges {
          node {
            id
            title
            quantity
            variant {
              id
              title
              product {
                handle
              }
              priceV2 {
                amount
                currencyCode
              }
              image {
                altText
                transformedSrc(maxWidth: 300, maxHeight: 400, crop: CENTER, preferredContentType: JPG)
              }
            }
          }
        }
      }
    }
  }
}

query getCartItemCount($checkoutId: ID!) {
  node(id: $checkoutId) {
    ... on Checkout {
      __typename
      lineItems(first: 250) {
        edges {
          node {
            quantity
          }
        }
      }
    }
  }
}

mutation createCart($input: CheckoutCreateInput!) {
  checkoutCreate(input: $input) {
    checkout {
      id
    }
  }
}

mutation addCartItem($checkoutId: ID!, $lineItem: CheckoutLineItemInput!) {
  checkoutLineItemsAdd(checkoutId: $checkoutId, lineItems: [$lineItem]) {
    checkout {
      id
    }
  }
}

mutation updateCartItem($checkoutId: ID!, $lineItem: CheckoutLineItemUpdateInput!) {
  checkoutLineItemsUpdate(checkoutId: $checkoutId, lineItems: [$lineItem]) {
    checkout {
      id
    }
  }
}

mutation removeCartItem($checkoutId: ID!, $lineItemId: ID!) {
  checkoutLineItemsRemove(checkoutId: $checkoutId, lineItemIds: [$lineItemId]) {
    checkout {
      id
    }
  }
}
