query getProductList($after: String) {
  products(first: 20, after: $after) {
    edges {
      node {
        id
        title
      }
      cursor
    }
    pageInfo {
      hasNextPage
    }
  }
}
