fragment PaginatedProductList on ProductConnection {
  edges {
    node {
      id
      handle
      title
      description(truncateAt: 120)
      priceRange {
        minVariantPrice {
          amount
          currencyCode
        }
      }
      images(first: 1) {
        edges {
          node {
            id
            altText
            transformedSrc(maxWidth: 768, maxHeight: 1024, crop: CENTER, preferredContentType: JPG)
          }
        }
      }
    }
    cursor
  }
  pageInfo {
    hasNextPage
  }
}

query getProductList($after: String) {
  products(first: 12, after: $after) {
    ...PaginatedProductList
  }
}

query getProductSingle($handle: String!) {
  productByHandle(handle: $handle) {
    title
    description
    seo {
      title
      description
    }
    images(first: 250) {
      edges {
        node {
          id
          altText
          transformedSrc(maxWidth: 768, maxHeight: 1024, crop: CENTER, preferredContentType: JPG)
        }
      }
    }
    variants(first: 250) {
      edges {
        node {
          id
          title
          priceV2 {
            amount
            currencyCode
          }
          image {
            id
          }
        }
      }
    }
  }
}

query getCollectionList($after: String) {
  collections(first: 12, after: $after) {
    edges {
      node {
        id
        handle
        title
        description
        image {
          id
          transformedSrc(maxWidth: 768, maxHeight: 1024, crop: CENTER, preferredContentType: JPG)
          altText
        }
      }
      cursor
    }
    pageInfo {
      hasNextPage
    }
  }
}

query getCollectionSingle($handle: String!, $productsAfter: String) {
  collectionByHandle(handle: $handle) {
    id
    handle
    title
    description
    products(first: 12, after: $productsAfter) {
      ...PaginatedProductList
    }
  }
}
